### ISSUE TITLE
Loading more granular historical data

### ISSUE THREAD

**Issue by gulo101** [kdeyev/eyeonwater#2]
Hello,

It looks like the API pulls the data only few times a day, resulting in fairly incomplete data with low granularity. Would it be possible to load 15 min interval data historically and insert it to Home Assistant? Thanks

**Comment by kdeyev** [comment]
Yes, EyeOnWater seems to limit the number of HTTP requests per day. 
You are right that I can get the history of the meter values, but HA sensor API does not allow me to modify the values of the sensor in the past.
If you have any idea how to implement it - I'm in :-)

**Comment by kdeyev** [comment]
Some references related to this topic:

https://community.home-assistant.io/t/wth-is-there-no-way-to-add-historical-data-to-energy-dashboard/468748
https://community.home-assistant.io/t/add-historic-data-to-energy-dashboard/423205
https://community.home-assistant.io/t/history-data-not-updating-when-fixing-historical-stats/413313

**Comment by bsp9493** [comment]
I'm sure someone noticed this before, but regardless of how often I poll with the integration, and regardless of my actual water usage, the reporting times always seem to be the same 7-8 am, 12-1am, 5-6pm, 7-8pm.

I know that I am using water outside of these time frames, and I also know that the integration is polling the service outside of these timeframes with no apparent errors.

Just seems strange that the reported timeframes of usage are always the same

**Comment by kdeyev** [comment]
Yes, It's the way EyeOnWater works: they read meters every 15 minutes and accumulate data somewhere in their backend, but they make the data available only several times a day. 
So the meter data becomes not the immediate meter reads but meter history. Unfortunately, HomeAssistant does not really support sensors with historical data reads.
For example: at 6 PM they share all the meter reads for 12 PM-6 PM. Yes, data has a granularity of 15 minutes, but I cannot update the meter reads for 12 PM, because HASS does not support it.

**Comment by bsp9493** [comment]
Ahhhhhh… I get it nowStrange indeed.dOn Nov 16, 2022, at 3:09 PM, Konstantin Deev ***@***.***> wrote:﻿
Yes, It's the way EyeOnWater works: they read meters every 15 minutes and accumulate data somewhere in their backend, but they make the data available only several times a day.
So the meter data becomes not the immediate meter reads but meter history. Unfortunately, HomeAssistant does not really support sensors with historical data reads.
For example: at 6 PM they share all the meter reads for 12 PM-6 PM. Yes, data has a granularity of 15 minutes, but I cannot update the meter reads for 12 PM, because HASS does not support it.

**Comment by rfnovo** [comment]
A possible solution would be for the sensor to collect hourly data for D-1 and then use the offset parameter of Utility Meter (https://www.home-assistant.io/integrations/utility_meter/) to adjust the data. 
Historical data would be accurate, but we won't have same day data. but we already don't have real time data, so that would not be a huge drawback

**Comment by kdeyev** [comment]
The most feasible solution I see so far - modification of the sensor history in the HA DB. as it described here: 
https://community.home-assistant.io/t/energy-counter-delayed-data/332108/12

I'm not sure regarding the robustness of the solution we could provide.

**Comment by andrewchumchal** [comment]
It does appear that homeassisant allow you to import historical data. If you take a look at this post here https://community.home-assistant.io/t/import-old-energy-readings-for-use-in-energy-dashboard/341406/9 he stats that it can be done with `async_add_external_statistics` and there are two plugins in the core that already use function as a example

**Comment by kdeyev** [comment]
@andrewchumchal, It looks very promising. Will try to utilize this API as soon as I can.
Thank you for sharing.

**Comment by kdeyev** [comment]
Hi All,

Is there anyone interested to go through beta testing of the solution?
The fix was released [here](https://github.com/kdeyev/eyeonwater/releases/tag/v1.3-beta5-statistics). Please feel free to enable pre-releases in HACS and test it.

**Comment by kdeyev** [comment]
Seems to work for me
![Screenshot 2023-08-15 at 7 11 11 PM](https://github.com/kdeyev/eyeonwater/assets/3978157/039f415b-fdce-419f-a72c-dbd369ebfb4d)

**Comment by bsp9493** [comment]
Looks great - will give it a shot!!!

Just noticed error after removing and reinstalling, not sure if this was there prior to installing the beta.


Logger: homeassistant.components.sensor
Source: custom_components/eyeonwater/sensor.py:48 
Integration: Sensor (documentation <https://www.home-assistant.io/integrations/sensor>, issues <https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22>) 
First occurred: 5:45:29 PM (1 occurrences) 
Last logged: 5:45:29 PM

Error while setting up eyeonwater platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eyeonwater/sensor.py", line 25, in async_setup_entry
    sensors.append(EyeOnWaterSensor(meter, coordinator))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/sensor.py", line 48, in __init__
    name=f"{WATER_METER_NAME} {self.meter.meter_info['meter_id']}",
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'meter_id'




> On Aug 15, 2023, at 5:12 PM, Konstantin Deev ***@***.***> wrote:
> 
> 
> Seems to work for me
> 
> 

Logger: homeassistant.components.sensor
Source: custom_components/eyeonwater/sensor.py:48 
Integration: Sensor (documentation <https://www.home-assistant.io/integrations/sensor>, issues <https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22>) 
First occurred: 5:45:29 PM (1 occurrences) 
Last logged: 5:45:29 PM

Error while setting up eyeonwater platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eyeonwater/sensor.py", line 25, in async_setup_entry
    sensors.append(EyeOnWaterSensor(meter, coordinator))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/sensor.py", line 48, in __init__
    name=f"{WATER_METER_NAME} {self.meter.meter_info['meter_id']}",
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'meter_id'

**Comment by randomstring** [comment]
I'm seeing the same error as @bsp9493 

Logger: homeassistant.components.binary_sensor
Source: custom_components/eyeonwater/binary_sensor.py:88
Integration: Binary sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 6:11:29 PM (1 occurrences)
Last logged: 6:11:29 PM
Error while setting up eyeonwater platform for binary_sensor

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eyeonwater/binary_sensor.py", line 62, in async_setup_entry
    sensors.append(EyeOnWaterBinarySensor(meter, coordinator, description))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/binary_sensor.py", line 88, in __init__
    name=f"Water Meter {self.meter.meter_info['meter_id']}",
                        ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'meter_id'
```

**Comment by kdeyev** [comment]
Yes, I'm facing the same issue. It was introduced recently and reported #27 .
Will fix it a bit later. For now, please reload the integration.

**Comment by kdeyev** [comment]
@disforw FYI

**Comment by disforw** [comment]
I am receiving the following:
Error occured during fetchig historinc data for sensor.water_meter_49281xxxxxxxxxxxxx8: Response is empty

**Comment by kdeyev** [comment]
@disforw Thank you for reporting!
I see the same and it started just after midnight. There is a period of time when the historical data is not collected/responded by EOW, so I'll need probably to suppress the error message.
BTW do you see the granular water usage data in your Energy Dashboard?

**Comment by disforw** [comment]
I do not, however, i installed the beta at 10:30pm Est, so if you’re right about midnight, I may have to wait for the next update.
OR, you’re stats were loaded on a previous update which is broken now. Try removing the integration and re-adding, see if your stats come back.

**Comment by kdeyev** [comment]
@disforw 
While starting the integration should import 30 days of historical data, but it's visible only in the Energy Dashboard.
![Screenshot 2023-08-15 at 7 11 11 PM](https://github.com/kdeyev/eyeonwater/assets/3978157/ac213a57-e74c-4785-ad21-0dfabb00f474)
Could you please, check several past days if you see granular hourly data?
Also could you please check the "Developer Tools"->Statistics if there are any error messages for the water sensor?
Thank you!

**Comment by disforw** [comment]
I checked stats for the last 2 weeks, no granular data. No issues reported in developer tools.

**Comment by bsp9493** [comment]
I am receiving the same error.s emptydOn Aug 16, 2023, at 4:39 AM, disforw ***@***.***> wrote:﻿
I am receiving the following:
Error occured during fetchig historinc data for sensor.water_meter_49281xxxxxxxxxxxxx8: Response is empty

**Comment by bsp9493** [comment]
Yes, was wondering if that may be the issue as I am Eyeonwater.ca and metric.Silly question.Where/how, do I run this within my system?dOn Aug 16, 2023, at 7:30 AM, Konstantin Deev ***@***.***> wrote:﻿
I will need some assistance on your end.
It may happen that the request to EOW is not correct, for example, because of units.
Could you please run test.py for your account and see if you get any historical data from:
        data = await meter.get_historical_data(
            client=client, units="GAL", date=yesterday
        )
        for d in data:
            print(str(d["start"]), d["sum"])

**Comment by bsp9493** [comment]
not a dev, but can usually fight my way through:)

found the details - I think.

https://www.home-assistant.io/integrations/python_script/￼
Python Scripts
home-assistant.io


Ok, updated system as noted above

Start by enabling the Python Scripts integration and create the first script.

Add to configuration.yaml: python_script:
Create the folder <config>/python_scripts
Create a file <config>/python_scripts/hello_world.py in the folder and give it this content:

Copied test.py from eyeonwater folder to new /python_scripts folder

changed test.py as follows to use .ca and metric

from http import cookies
import aiohttp
import asyncio

from eow import Account, Client, Meter

async def main():
    account = Account(eow_hostname="eyeonwater.ca", ***@***.***", password=“xxxxxxxxxxxxxxxxxxxxx", metric_measurement_system=True)
    websession = aiohttp.ClientSession()
    client = Client(websession=websession, account=account)

    await client.authenticate()
        
    meters = await account.fetch_meters(client=client)
    print(f"{len(meters)} meters found")
    for meter in meters:
        await meter.read_meter(client=client)
        print(f"meter {meter.meter_uuid} shows {meter.reading}")
        print(f"meter leaks: {meter.has_leak}")

    await websession.close()
       

loop = asyncio.get_event_loop()
loop.run_until_complete(main())




from developer tools - call service “test.py”

it appears to run (I get a green checkmark), but where does the output go???

I also see the following error in the log after running script.

Logger: homeassistant.components.python_script
Source: components/python_script/__init__.py:112 
Integration: Python Scripts (documentation, issues) 
First occurred: 8:22:23 AM (1 occurrences) 
Last logged: 8:22:23 AM

Error loading script test.py: Line 7: AsyncFunctionDef statements are not allowed.



Let me know what I need to do.

d

**Comment by bsp9493** [comment]
.8 beta gives new error and will not set upThis error originated from a custom integration.Logger: homeassistant.config_entriesSource: custom_components/eyeonwater/eow.py:177 Integration: EyeOnWater (documentation) First occurred: 8:30:27 AM (3 occurrences) Last logged: 8:32:19 AMError setting up entry ***@***.*** for eyeonwaterTraceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup    result = await component.async_setup_entry(hass, self)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/config/custom_components/eyeonwater/__init__.py", line 48, in async_setup_entry    await eye_on_water_data.import_historical_data(days_to_load=30)  File "/config/custom_components/eyeonwater/coordinator.py", line 65, in import_historical_data    statistics = await self.get_historical_data(meter, days_to_load)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/config/custom_components/eyeonwater/coordinator.py", line 106, in get_historical_data    data = await meter.get_historical_data(           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/config/custom_components/eyeonwater/eow.py", line 177, in get_historical_data    data = json.loads(data)           ^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads    return _default_decoder.decode(s)           ^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)dOn Aug 16, 2023, at 8:23 AM, David Morhun ***@***.***> wrote:﻿not a dev, but can usually fight my way through:)found the details - I think.<default-social.png>Python Scriptshome-assistant.ioOk, updated system as noted aboveStart by enabling the Python Scripts integration and create the first script.Add to configuration.yaml: python_script:Create the folder <config>/python_scriptsCreate a file <config>/python_scripts/hello_world.py in the folder and give it this content:Copied test.py from eyeonwater folder to new /python_scripts folderchanged test.py as follows to use .ca and metricfrom http import cookiesimport aiohttpimport asynciofrom eow import Account, Client, Meterasync def main():    account = Account(eow_hostname="eyeonwater.ca", ***@***.***", password=“xxxxxxxxxxxxxxxxxxxxx", metric_measurement_system=True)    websession = aiohttp.ClientSession()    client = Client(websession=websession, account=account)    await client.authenticate()            meters = await account.fetch_meters(client=client)    print(f"{len(meters)} meters found")    for meter in meters:        await meter.read_meter(client=client)        print(f"meter {meter.meter_uuid} shows {meter.reading}")        print(f"meter leaks: {meter.has_leak}")    await websession.close()       loop = asyncio.get_event_loop()loop.run_until_complete(main())from developer tools - call service “test.py”it appears to run (I get a green checkmark), but where does the output go???I also see the following error in the log after running script.Logger: homeassistant.components.python_scriptSource: components/python_script/__init__.py:112 Integration: Python Scripts (documentation, issues) First occurred: 8:22:23 AM (1 occurrences) Last logged: 8:22:23 AMError loading script test.py: Line 7: AsyncFunctionDef statements are not allowed.Let me know what I need to do.dOn Aug 16, 2023, at 7:53 AM, Konstantin Deev ***@***.***> ***@***.*** It's definitely because of measurement units, we will need to find a proper way to request historical data in liters or m^3, I bet that EOW returns an empty response if the request is not supported.
Unfortunately, I can test only gallons since my account is in gallons.The simplest way to run test.py is by downloading the latest source and running python test.py locally.
But it may be a bit of a challenge if you don't have a software dev background.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by kdeyev** [comment]
@bsp9493 
Thank you for the effort!
I apologize, I forgot to mention that you need to use https://github.com/kdeyev/eyeonwater/tree/feature/import-statistics branch, since the changes were not been officially released yet.
Could you please take the source code from this branch and modify test.py again for your account, eow.ca, and metric system? 
After you have the test.py adjusted, you don't really need any HAS stuff, test.py is self-contained. 
Once you have the source code landed anywhere, you just need to run `python test.py`. 
There are multiple ways to do it: probably the simplest is to use a command line terminal: `cd source_code_location` and `python test.py`.
Thank you!

**Comment by kdeyev** [comment]
@bsp9493 Do you mind sharing temporary credentials for your EOW account for debugging purposes? 
If you are ok with it, please contact me by kn.deev @ gmail

**Comment by disforw** [comment]
I am located in the US and using gal, but still no response. I also can not run the test bec I don’t have a proper dev environment. However, just before you started pushing this PR forward, I played around with your old code and successfully got a response from the API, so I moved the function to eow.py on Master. Let me play around a bit and get back to you.

**Comment by kdeyev** [comment]
@disforw Thank you for the answer.
Now I'm puzzled why the data is not imported by `async_import_statistics(self.hass, metadata, statistics)`.
Usually home assistant prints error messages if anything goes wrong. 
Or maybe metadata is somehow wrong on your end:
```
                metadata = StatisticMetaData(
                    has_mean=False,
                    has_sum=True,
                    name=name,
                    source="recorder",
                    statistic_id=statistic_id,
                    unit_of_measurement=meter.native_unit_of_measurement,
                )
```
I don't have any other ideas so far.

**Comment by disforw** [comment]
When I use the function that is currently in the master branch inside of eow.py called get_consumption, as it stands, I get back a promising result…
`statistics = await meter.get_consumption(date=yesterday.strftime('%m/%d/%Y'), client=self.client)
_LOGGER.debug(statistics)`
Results to this are…

**Comment by kdeyev** [comment]
That looks correct, does the 7074.23 gallons meter value correlate to the meter reads in EOW?
Could you please switch to the `feature/import-statistics` branch and verify it once again? (Just in case I messed something up in the branch).
Could you please also install the [v1.3-beta8](https://github.com/kdeyev/eyeonwater/tree/v1.3-beta8) to your HACS?
Do you see any suspicious logs related to the integration? Does the water meter sensor load ok and show the correct value? It also makes sense to look at Dev Tools -> Statistics for this sensor, it shows units misfit if there are.
The integration does not change the sensor history, but it updates the statistics associated with the sensor. It means that the result will be visible only in the standard Energy Dashboard. I just want no make sure that we are on the same page. 

Here sensor history is not updated.
![Screenshot 2023-08-16 at 5 41 00 PM](https://github.com/kdeyev/eyeonwater/assets/3978157/48a788ee-823e-4d79-a26f-3a4c30192695)
But the Energy Dashboard for the same day looks ok
![Screenshot 2023-08-16 at 5 46 13 PM](https://github.com/kdeyev/eyeonwater/assets/3978157/147cafd9-bacd-4b0f-85f2-a6a8171da078)

**Comment by disforw** [comment]
Ok so it seems like your loading statistics in to a “sensor.water_meter_{meter_uuid}” when the actual entity_id being generated is “sensor.water_meter{meter_id}”. 
check your energy dashboard setup that you have the correct entity added there.

**Comment by kdeyev** [comment]
@disforw Yup, you are right, the ids were messed up. I fixed it and reconfigured the Energy Dashboard on my end.
It seems to work. 
I've released v1.3-beta10. could you give it a try?

**Comment by disforw** [comment]
@kdeyev I am erroring out here, ive tried readding, but no good. Using beta 10

This error originated from a custom integration.

Logger: custom_components.eyeonwater
Source: components/recorder/statistics.py:2140 
Integration: EyeOnWater (documentation) 
First occurred: 10:38:42 PM (1 occurrences) 
Last logged: 10:38:42 PM

Unexpected error fetching EyeOnWater data: Invalid statistic_id
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/eyeonwater/__init__.py", line 68, in async_update_data
    await eye_on_water_data.import_historical_data()
  File "/config/custom_components/eyeonwater/coordinator.py", line 79, in import_historical_data
    async_import_statistics(self.hass, metadata, statistics)
  File "/usr/src/homeassistant/homeassistant/components/recorder/statistics.py", line 2140, in async_import_statistics
    raise HomeAssistantError("Invalid statistic_id")
homeassistant.exceptions.HomeAssistantError: Invalid statistic_id

**Comment by kdeyev** [comment]
Fixed in v2.0.0

**Comment by kdeyev** [comment]
@disforw Ooops, I've just released v2.0

**Comment by disforw** [comment]
I think I got it.. My meter_id has letters in it. The entity-id is lower case and the statistic-id is upper case.

**Comment by kdeyev** [comment]
Ouch. I think it makes sense to switch to uuid, which will be unified.

**Comment by bsp9493** [comment]
Weird result on start up…History is there and looks good, but TODAY, shows negative valuesdOn Aug 16, 2023, at 8:06 PM, disforw ***@***.***> wrote:﻿
So its hard to say, thatwould really depend on someone who has multiple meters on one account, which one is unique and which is account wide? To ME, it looked like meter-id was the per-meter unique id. I am basing this on the way the results were structured.

**Comment by kdeyev** [comment]
I saw the same thing, but I didn't find out why it happened.
But I found a way to fix it: in Dev tools -> Statistics there's a button
for each sensor for fixing the statistics points. So, I found and removed
the problematic point.

**Comment by bsp9493** [comment]
Newest integration seems to be working well.  Thanx for all the work on this!!!One issue still present.  While the history of the entity looks to be fine, the most current reading in the energy dashboard is a huge negative value.  As updates come in from water meter, this value moves to be the most current.I have no errors in the logs, and I am unable to locate any rogue data points that would cause this.If I go to previous day(s) everything is populated correctly.Any suggestions where to look?dOn Aug 16, 2023, at 8:16 PM, Konstantin Deev ***@***.***> wrote:﻿
I saw the same thing, but I didn't find out why it happened.

But I found a way to fix it: in Dev tools -> Statistics there's a button

for each sensor for fixing the statistics points. So, I found and removed

the problematic point.
