### ISSUE TITLE
Eye On Water Entities Not Supported in New Core 2022.11.x Energy Dashboard

### ISSUE THREAD

**Issue by nsheldon** [kdeyev/eyeonwater#3]
It looks like the water meter entity created by Eye On Water is not supported by the Energy dashboard in Home Assistant Core 2022.11.0 (or 2022.11.1). See screenshots attached below.  The Home Assistant help topic on this says to refer developers to

https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

for details on how to made their integrations compatible with the new water meter tracking in the Energy dashboard.

![No matching statistics found](https://user-images.githubusercontent.com/2738776/200078422-4963ea0b-0e33-45f1-a0ec-1dc1dd9093a3.png)
![Water meter entities](https://user-images.githubusercontent.com/2738776/200078433-30124929-8f0c-46d2-bb71-eba8af787e73.png)

**Comment by bsp9493** [comment]
first of all...  THANX for this integration!!!

I'm in Canada, and needed to make a few changes to get it to work.  Had to modify eow.py and sensor.py and customize.yaml as follows

**eow.py**

change to canadian website
BASE_HOSTNAME = "eyeonwater.ca"

add
MEASUREMENT_CUBICMETERS = "CM"

replace
  elif read_unit.upper() == MEASUREMENT_GALLONS:
with
  elif read_unit.upper() == MEASUREMENT_CUBICMETERS:

this got me in and working, but homeassistant energy would not see the entity.



**sensor.py**

change
_attr_native_unit_of_measurement = 'm\u00b3'

to allow display of units as cubic meters m^3.  this alone would still not show the sensor in the energy dashboard.

after doing some reading, it appears home assistant wants to see this as a DEVICE_CLASS_WATER.  to make this change, I updated my **customize.yaml** file in the HA root directory with the following entry.

  sensor.water_meter_12345678:
    device_class: water


This allows the entity to be added to the energy dashboard.  Not sure if the numbers are displayed correctly (due to me reading cubic meters, but, I do get a number that corresponds to what is actually on the eyeonwater.ca page.

I hope this helps going forward, and again, thanx for writing this integration!!!

**Comment by kdeyev** [comment]
Hi. 
Sorry for the late answer, I was a bit busy on my main job.
I've fixed the issue with "device_class".
I also extended the configuration for support eyeonwater.ca and metric measurement system support.
@bsp9493 could you please verify that it works as expected.
I have any fix - please feel free to create a PR.

**Comment by bsp9493** [comment]
Thanx for the update…Seems to load and connect, but it is not creating the water meter…. Debug log below2022-11-12 20:52:19.020 DEBUG (MainThread) [custom_components.eyeonwater.eow] Successfully retrieved login token2022-11-12 20:52:19.494 DEBUG (MainThread) [custom_components.eyeonwater] Discovered 0 meter(s)2022-11-12 20:52:19.512 DEBUG (MainThread) [custom_components.eyeonwater] Fetching latest data2022-11-12 20:52:19.512 DEBUG (MainThread) [custom_components.eyeonwater] Finished fetching Eye On Water data in 0.000 seconds (success: True)dOn Nov 12, 2022, at 8:16 PM, Konstantin Deev ***@***.***> wrote:﻿
Closed #3 as completed.

**Comment by bsp9493** [comment]
After update via hacs, I removed the integration from home assistant, then traded the integration.I noticed an additional line in the config… .comUsernamePasswordI still had to modify the eow.py …It looks like Eyeonwater.com is still the default.I updated that to .ca, and integration appears to be working with that one change dOn Nov 12, 2022, at 8:57 PM, David Morhun ***@***.***> wrote:﻿Thanx for the update…Seems to load and connect, but it is not creating the water meter…. Debug log below2022-11-12 20:52:19.020 DEBUG (MainThread) [custom_components.eyeonwater.eow] Successfully retrieved login token2022-11-12 20:52:19.494 DEBUG (MainThread) [custom_components.eyeonwater] Discovered 0 meter(s)2022-11-12 20:52:19.512 DEBUG (MainThread) [custom_components.eyeonwater] Fetching latest data2022-11-12 20:52:19.512 DEBUG (MainThread) [custom_components.eyeonwater] Finished fetching Eye On Water data in 0.000 seconds (success: True)dOn Nov 12, 2022, at 8:16 PM, Konstantin Deev ***@***.***> wrote:﻿
Closed #3 as completed.
